# Generated by Django 3.2.3 on 2021-05-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billaddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_street', models.TextField(max_length=150)),
                ('bill_city', models.CharField(max_length=150)),
                ('bill_state', models.CharField(max_length=150)),
                ('bill_zipcode', models.CharField(max_length=25)),
                ('bill_country', models.CharField(max_length=100)),
                ('ship_street', models.TextField(max_length=150)),
                ('ship_city', models.CharField(max_length=150)),
                ('ship_state', models.CharField(max_length=150)),
                ('ship_zipcode', models.CharField(max_length=25)),
                ('ship_country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150)),
                ('VAT', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('website', models.CharField(max_length=100)),
                ('groups', models.CharField(max_length=200)),
                ('currency', models.CharField(max_length=25)),
                ('language', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('zipcode', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item_groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('long_description', models.TextField(max_length=250)),
                ('rate', models.IntegerField()),
                ('tax1', models.IntegerField()),
                ('tax2', models.IntegerField()),
                ('unit', models.IntegerField()),
            ],
        ),
    ]
